<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- better macro name? -->
    <DefineConstants>$(DefineConstants);MIAO_SERVER;INSPECTOR</DefineConstants>

    <MiaoNetSharedPath>../MiaoNet.Shared</MiaoNetSharedPath>
  </PropertyGroup>

  <ItemGroup>
    <NoNotCompile Include="$(MiaoNetSharedPath)/Helpers/PacketHandlerRegister.cs" />
    <NoNotCompile Include="$(MiaoNetSharedPath)/Helpers/PacketDispatcher.cs" />
    <NoNotCompile Include="$(MiaoNetSharedPath)/PlayerExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MiaoNetSharedPath)/**/*.cs" Exclude="@(NoNotCompile)" LinkBase="0-Shared" />
    <Compile Include="../MiaoNet.Server/Primitives/*.cs" LinkBase="1-ServerPrimitives" />
  </ItemGroup>

</Project>
