<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);MIAO_MOCKCLIENT</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../MiaoNet.Shared/**/*.cs"
             Exclude="../MiaoNet.Shared/PlayerExtensions.cs"
             LinkBase="0-Shared" />
		<Compile Include="../MiaoNet.ClientShared/**/*.cs" LinkBase="1-ClientShared" />
	</ItemGroup>

	<PropertyGroup>
		<AnalysisModeGlobalization>None</AnalysisModeGlobalization>
	</PropertyGroup>

	<ItemGroup Condition="$(UseLocalhostPfx) == 'true'">
		<EmbeddedResource Include="../localhost.pfx" LogicalName="localhost.pfx" Visible="false" />
	</ItemGroup>

</Project>
