<Project>

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  
  <PropertyGroup>
    <ProjectRootDirectory>$(MSBuildThisFileDirectory)</ProjectRootDirectory>
    <PathMap>$(ProjectRootDirectory)=~/</PathMap>
  </PropertyGroup>

  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
  
</Project>