<Project>

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <UseLocalhostPfx>false</UseLocalhostPfx>
    <UseLocalhostPfx Condition="$(Configuration) == 'Debug'">true</UseLocalhostPfx>
  </PropertyGroup>

  <PropertyGroup>
    <ProjectRootDirectory>$(MSBuildThisFileDirectory)</ProjectRootDirectory>
    <PathMap Condition="$(Configuration)=='Release'">$(ProjectRootDirectory)=~/</PathMap>
  </PropertyGroup>

  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

</Project>