@hostname=localhost
@port=21474
@host={{hostname}}:{{port}}

###

# status
GET http://{{host}}/status

###

# kick player
@pid=6
@reason=Reason here.
POST http://{{host}}/player/kick?id={{pid}}&reason={{reason}}

###

# announce
@msg=Server is closing!
POST http://{{host}}/announce?msg={{msg}}

###

# metrics
GET http://{{host}}/metrics