@hostname=localhost
@port=21474
@host={{hostname}}:{{port}}

###

# status
GET http://{{host}}/status

###

# kick player (by cid)
@cid=1
@reason=Reason here.
DELETE http://{{host}}/player?cid={{cid}}&reason={{reason}}

###

# announce
@msg=Server is closing!
POST http://{{host}}/announce?msg={{msg}}

###

# metrics
GET http://{{host}}/metrics